### ISSUE TITLE
关于“如何声明@ti.kernel中最外层循环串行”的解决方案

### ISSUE THREAD

**Issue by Yousazoe** [0xrabbyte/TinyRayTracer-Taichi#1]
可以在外面加一个假循环串行最外层：
```python
for _ in range(1): 
  for i in range(100):  # 串行
    ...
```

**Comment by 0xrabbyte** [comment]
倒是我在[太极图形课S1第03讲]()看到ti.init()中可以写一个cpu_max_num_thread=1来保证串行。但不知道如何单独运用到一个@ti.kernel中

**Comment by 0xrabbyte** [comment]
Taichi v.1.0.0中提供了`ti.loop_config(serialize=True)`可以十分优雅地解决这个问题！😆
